image: "docker/attest-provider:0.0.11@sha256:fc5cf776585965e15f667709c3299c275322163614015702dffe856f6e95bbab"

certDir: /certs
clientCAFile: /tmp/gatekeeper/ca.crt
port: 8090
handlerTimeout: 25
replicas: 1

# uncomment these lines to use other TUF root environments
# tufRoot: dev
# tufMetadataSource: https://docker.github.io/tuf-dev/metadata
# tufTargetsSource: https://docker.github.io/tuf-dev/targets
#
# tufRoot: staging
# tufMetadataSource: registry-1.docker.io/docker/tuf-metadata-staging
# tufTargetsSource: registry-1.docker.io/docker/tuf-targets-staging

tufRoot: prod
tufChannel: ""
tufMetadataSource: registry-1.docker.io/docker/tuf-metadata
tufTargetsSource: registry-1.docker.io/docker/tuf-targets

attestationStyle: referrers

provider:
  timeout: 30
  tls:
    caBundle: ""
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false # need to fix go-tuf temp dir
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532
  seccompProfile:
    type: RuntimeDefault
