image: "docker/attest-provider:0.0.6@sha256:1403ff1d17ffb9d330e90817ed05d080dec2bd4c9f7e611be07788111040342f"

certDir: /certs
clientCAFile: /tmp/gatekeeper/ca.crt
port: 8090
replicas: 1

# uncomment these lines to use the dev TUF root
# tufRoot: dev
# tufMetadataSource: https://docker.github.io/tuf-dev/metadata
# tufTargetsSource: https://docker.github.io/tuf-dev/targets

tufMetadataSource: https://docker.github.io/tuf-staging/metadata
tufTargetsSource: https://docker.github.io/tuf-staging/targets

attestationStyle: referrers

provider:
  timeout: 30
  tls:
    caBundle: ""
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false # need to fix go-tuf temp dir
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532
  seccompProfile:
    type: RuntimeDefault
